# Generated by Django 4.2 on 2023-04-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_facing', '0002_projects_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
