# Generated by Django 4.2 on 2023-04-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_facing', '0004_education_experience_research_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='year',
            new_name='end_year',
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
