# Generated by Django 4.2 on 2023-04-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_facing', '0005_rename_year_education_end_year_education_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='author_names',
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
