# Generated by Django 4.2.1 on 2023-05-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authuser',
            managers=[
            ],
        ),
    ]
