# Generated by Django 4.2.1 on 2023-05-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_authuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='email',
        ),
    ]
