# Generated by Django 4.2.1 on 2023-05-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_authuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
