# Generated by Django 4.2.1 on 2023-05-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_educations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Educations',
        ),
    ]
