# Generated by Django 4.2.1 on 2023-05-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_authuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
